/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import model.Biblioteca;
import model.Cliente;
import model.EmprestimoLivroAdaptador;
import model.Funcionario;
import model.Gerente;
import model.Livro;

/**
 *
 * @author leoni
 */
public class Gerenciar extends javax.swing.JDialog {

    /**
     * Creates new form Gerenciar
     */
    public Gerenciar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Cadastrar Livros...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cadastrar Clientes...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Emprestar para Clientes...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(310, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
            // Adicionar um livro emprestado
            String titulo = JOptionPane.showInputDialog("Digite o título do livro:");
            String autor = JOptionPane.showInputDialog("Digite o autor do livro:");
            String genero = JOptionPane.showInputDialog("Digite o gênero do livro:");
            String dataDePublicacao = JOptionPane.showInputDialog("Digite a data de publicação do livro:");
            String sinopse = JOptionPane.showInputDialog("Digite a sinopse do livro:");
            int numeroDePaginas = Integer.parseInt(JOptionPane.showInputDialog("Digite o número de páginas do livro:"));
            String editora = JOptionPane.showInputDialog("Digite a editora do livro:");
            String ISBN = JOptionPane.showInputDialog("Digite o ISBN do livro:");
            String premiacoes = JOptionPane.showInputDialog("Digite as premiações do livro:");
            String recepcaoCritica = JOptionPane.showInputDialog("Digite a recepção crítica do livro:");
            String capa = JOptionPane.showInputDialog("Digite a capa do livro:");

            Livro novoLivro = new Livro(titulo, autor, genero, dataDePublicacao, sinopse, numeroDePaginas, editora, ISBN, premiacoes, recepcaoCritica, capa);
            Biblioteca unicaBiblioteca = Biblioteca.getInstanciaDaBiblioteca();
            unicaBiblioteca.adicionarLivro(novoLivro);
            System.out.println("Livro adicionado ao cliente:");
            System.out.println(novoLivro.toString());
        } catch (NumberFormatException e) {
            System.out.println("Erro ao formatar o número de páginas.");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          
            try {
                
                String nome = JOptionPane.showInputDialog("Digite o nome do cliente:");
                String sobrenome = JOptionPane.showInputDialog("Digite o sobrenome do cliente:");
                String dataDeNascimentoStr = JOptionPane.showInputDialog("Digite a data de nascimento do cliente (dd/MM/yyyy):");
                Date dataDeNascimento = new SimpleDateFormat("dd/MM/yyyy").parse(dataDeNascimentoStr);
                String numeroDeIdentidade = JOptionPane.showInputDialog("Digite o número de identidade do cliente:");
                String telefone = JOptionPane.showInputDialog("Digite o telefone do cliente:");
                String email = JOptionPane.showInputDialog("Digite o email do cliente:");
                String numeroDeMembro = JOptionPane.showInputDialog("Digite o número de membro do cliente:");
                String dataDeAssociacaoStr = JOptionPane.showInputDialog("Digite a data de associação do cliente (dd/MM/yyyy):");
                Date dataDeAssociacao = new SimpleDateFormat("dd/MM/yyyy").parse(dataDeAssociacaoStr);

                List<Livro> livrosEmprestados = new ArrayList<>(); // Supondo que seja uma lista vazia para o exemplo

                Cliente novoCliente = new Cliente(nome, sobrenome, dataDeNascimento, numeroDeIdentidade, telefone, email, numeroDeMembro, dataDeAssociacao, livrosEmprestados);

                if (nome != null && email != null && telefone != null) {
                    System.out.println("Cliente cadastrado com sucesso:");
                    System.out.println(novoCliente.toString());
                } else {
                    System.out.println("Cadastro de cliente cancelado ou incompleto.");
                }
            } catch (ParseException e) {
                System.out.println("Erro ao formatar a data.");

            }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          // Criar instâncias de livros e pessoas
        Livro livro = new Livro("Título do Livro", "Autor do Livro", "Gênero", "01/01/2020", "Sinopse", 300, "Editora", "123456789", "Premiações", "Recepção Crítica", "Capa");
        Cliente cliente = new Cliente("Nome do Cliente", "Sobrenome do Cliente", new Date(), "123456789", "Telefone", "email@example.com", "12345", new Date(), new ArrayList<>());
        Gerente gerente = new Gerente();
        Funcionario funcionario = new Funcionario();

        // Definir nomes para o gerente e funcionário
        gerente.setNome("Nome do Gerente");
        funcionario.setNome("Nome do Funcionário");

        // Criar instância do adaptador de empréstimo
        EmprestimoLivroAdaptador adaptador = new EmprestimoLivroAdaptador();

        // Emprestar livro para o cliente
        String resultadoCliente = adaptador.emprestaLivro(livro, cliente);
        System.out.println(resultadoCliente);

        // Emprestar livro para o gerente
        String resultadoGerente = adaptador.emprestaLivro(livro, gerente);
        System.out.println(resultadoGerente);

        // Emprestar livro para o funcionário
        String resultadoFuncionario = adaptador.emprestaLivro(livro, funcionario);
        System.out.println(resultadoFuncionario);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gerenciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gerenciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gerenciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gerenciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Gerenciar dialog = new Gerenciar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
